@startuml 
actor :Nhà kinh doanh: as Business
left to right direction
(Quản lý tài khoản) as QLTK
(Quản lý địa điểm) as QLDD
(Thống kê và báo cáo) as TKBC
(Chăm sóc khách hàng) as CSKH

Business -->  QLTK
QLTK ..> (Đăng nhập)
QLTK ..> (Đăng ký)
QLTK ..> (Lấy lại mật khẩu)
(Lấy lại mật khẩu) <.. (Xác thực qua email) : <<include>>


Business --> QLDD
QLDD ..> (Thêm địa điểm)
(Thêm địa điểm) <.. (Nhập đẩy đủ thông tin): <<include>>
QLDD ..> (Sửa địa điểm)
QLDD ..> (Xóa địa điểm)

Business --> TKBC
TKBC ..> (Xuất báo cáo)
(Xuất báo cáo) <.. (Chọn khoảng thời gian): <<include>>
TKBC ..> (Thống kê của nhà kinh doanh)
(Thống kê của nhà kinh doanh) <.. (Chọn khoảng thời gian): <<include>>
TKBC ..> (Thống kê của địa điểm)
(Thống kê của địa điểm) <.. (Chọn khoảng thời gian): <<include>>

Business --> CSKH
CSKH ..> (Trả lời tin nhắn)
CSKH ..> (Phản hồi đánh giá)

@enduml


