@startuml 
actor :Khách hàng: as Customer
left to right direction
(Xác thực) as XT
(Đặt chỗ) as DC
(Nhắn tin) as NTin 
(Review địa điểm) as RV 
(Quản lý thông tin) as QLTT


Customer -->  XT
XT ..> (Đăng nhập)
XT ..> (Đăng ký)
XT ..> (Lấy lại mật khẩu)
(Lấy lại mật khẩu) <.. (Xác thực qua email) : <<include>>


Customer --> DC
DC <.. (Chọn phòng) : <<include>>
DC <.. (Điền thông tin) : <<include>>
DC <.. (Chọn phương thức thành toán) : <<include>>
DC <.. (Hủy đặt): <<extend>>

Customer --> NTin

Customer --> RV 

Customer --> QLTT
QLTT <.. (Đổi mật khẩu) : <<extend>>
(Đổi mật khẩu) <.. (Nhập lại mật khẩu) : <<include>>

(DC) <.. (RV): <<extend>>

@enduml


