@startuml

'--Actor declare section--'
actor :Khách hàng: as Customer
actor :Nhà kinh doanh: as Business 
actor :Nhà quản trị: as Admin

'--Use case declare section--'
    'Genaral usecase'
    'Customer usecase'
        'base usecase'
        (Xác thực) as XT
        (Tìm kiếm địa điểm) as TKDD
        (Danh sách yêu thích) as DSYT
        (Đặt chỗ) as DC
        (Nhắn tin) as NTin
        (Bình luận) as BLuan
        (Review địa điểm) as RV 
        (Thay đổi thông tin) as TDTT
    'Business usecase'
        'base usecase'
        (Quản lý địa điểm) as QLDD
        (Thống kê và báo cáo) as TKBC
        (Nhắn tin) as NTin
        (Bình luận) as BLuan

    'Admin use case'
        'base usecase'
        (Cập nhật thông tin khách hàng) as CNKH
        (Thêm nhà kinh doanh) as QLNKD
        (Thống kê và báo cáo) as TKBC

'--Usecase section'
    '--Customer'
    Customer --> XT
    Customer -->TKDD
    Customer -up->DC
    Customer -up->DSYT
    Customer -->NTin
    Customer -->BLuan
    Customer -up->RV
    Customer -->TDTT
    '--Business--'
    Business -up->XT
    Business -up->QLDD
    Business -up->TKDD
    Business -up->TKBC
    Business -up->NTin
    Business -up->BLuan
    Business -up->TDTT

    '--Admin--'
    Admin -up-> XT
    Admin -up->QLDD
    Admin -down-> CNKH
    Admin -down->QLNKD
    Admin -up->TKBC
@enduml