@startuml
title Authentication Sequence Diagram

actor "Người dùng" as User
participant "Giao diện đăng nhập" as UI
participant "Authentication" as Auth
participant "Account entity" as AE
participant "Database" as DB

User -> UI : 1. Yêu cầu đăng nhập
activate UI
UI -> Auth : 2. Chuyển đổi yêu cầu
activate Auth 
Auth -> AE : 3. Yêu cầu hashing
activate AE
AE -> DB : 4. Kiểm tra thông tin
activate DB 
DB --> AE : 5. Thông báo \nthành công/thất bại
deactivate DB
AE --> Auth: 6. Thông báo \nthành công/thất bại
deactivate AE
Auth --> UI: 6. Phản hồi \nthành công/thất bại
deactivate Auth
UI --> User : 6. Hiển thị thông báo
deactivate UI

@enduml