@startuml
title Xác thực
hide empty members
state "Idle" as State1
state "Authencating" as State2
state "Success" as State3
state "Failed" as State4

state "Email sent" as State5 {
    state "Pending" as State6
    state "Confirmed" as State7
    state "Changed" as State8

    State4 --> State6 : Người dùng \ntạo lại mật khẩu
    State6 -right-> State7 : Người dùng thay \nđổi mật khẩu
    State7 --> State8 : Hệ thống kiểm tra
}

state "Created" as State9
[*] --> State1
State1 --> State2 : Xác nhận đăng nhập
State2 --> State3 : Thông tin chính xác
State2 --> State4 : Thông tin sai
State4 -up-> State1 : Nhập lại thông tin
State4 --> State9 : Người dùng tạo\n tài khoản mới
State9 --> State1
State3 --> [*]






@enduml
